spring.datasource.url=jdbc:h2:mem:festivalflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never

logging.level.org.springframework.web=INFO
logging.level.org.springframework.jdbc.datasource.init=INFO
logging.level.com.example.festival_management=INFO

spring.main.banner-mode=console
